name: Test
on:
  pull_request:
  push:
jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@9
        with:
          nix_path: nixpkgs=channel;nixos-unstable
      - run: nix-build