name: Test
on:
  pull_request:
  push:
  issue_comment:
    types: [created, edited]
jobs:
  test:
    if: "'pull_request|push'.contains(github.event_name) || github.event.comment.body == 'rebuild'"
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v9
      - run: nix-build